#requires -Version 3
#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 5b2dfed2-2bb7-498b-b488-c36198745301
# Source File: C:\Users\Newingha\Documents\SAPIEN\PowerShell Studio\Files\GetACL.psf
#------------------------------------------------------------------------

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2019 v5.6.167
     Generated on:       2/14/2020 11:38 AM
     Generated by:       Support.newingha
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2019
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-GetACL_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formDisplayACL = New-Object 'System.Windows.Forms.Form'
	$buttonBrowseLocation = New-Object 'System.Windows.Forms.Button'
	$labelLocation = New-Object 'System.Windows.Forms.Label'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$buttonFindPermissions = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formDisplayACL_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	
	
	Function displayPermissions
	{
		$Path = $textbox1.Text
		$FolderPath = Get-ChildItem -Directory -Path $Path -Recurse -Force
		$Output = @()
		ForEach ($Folder in $FolderPath)
		{
			$Acl = Get-Acl -Path $Folder.FullName
			ForEach ($Access in $Acl.Access)
			{
				$Properties = [ordered]@{ 'Folder Name' = $Folder.FullName; 'Group/User' = $Access.IdentityReference; 'Permissions' = $Access.FileSystemRights; 'Inherited' = $Access.IsInherited }
				$Output += New-Object -TypeName PSObject -Property $Properties
			}
		}
		$Output | Out-GridView
	}
	$buttonFindPermissions_Click={
		$Path = $textbox1.Text
		displayPermissions
	}
	
	Function Get-Folder($initialDirectory)
	{
		[System.Reflection.Assembly]::LoadWithPartialName("System.windows.forms") | Out-Null
		
		$foldername = New-Object System.Windows.Forms.FolderBrowserDialog
		$foldername.Description = "Select a folder"
		$foldername.rootfolder = "MyComputer"
		
		if ($foldername.ShowDialog() -eq "OK")
		{
			$textbox1.Text += $foldername.SelectedPath
		}
		return $folder
	}
	
	
	
	$buttonBrowseLocation_Click={
		Get-Folder
	}
	
	$labelLocation_Click={
		#TODO: Place custom script here
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formDisplayACL.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonBrowseLocation.remove_Click($buttonBrowseLocation_Click)
			$labelLocation.remove_Click($labelLocation_Click)
			$buttonFindPermissions.remove_Click($buttonFindPermissions_Click)
			$formDisplayACL.remove_Load($formDisplayACL_Load)
			$formDisplayACL.remove_Load($Form_StateCorrection_Load)
			$formDisplayACL.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formDisplayACL.SuspendLayout()
	#
	# formDisplayACL
	#
	$formDisplayACL.Controls.Add($buttonBrowseLocation)
	$formDisplayACL.Controls.Add($labelLocation)
	$formDisplayACL.Controls.Add($textbox1)
	$formDisplayACL.Controls.Add($buttonFindPermissions)
	$formDisplayACL.AutoScaleDimensions = '6, 13'
	$formDisplayACL.AutoScaleMode = 'Font'
	$formDisplayACL.ClientSize = '381, 79'
	$formDisplayACL.Name = 'formDisplayACL'
	$formDisplayACL.Text = 'Display ACL'
	$formDisplayACL.add_Load($formDisplayACL_Load)
	#
	# buttonBrowseLocation
	#
	$buttonBrowseLocation.Location = '258, 11'
	$buttonBrowseLocation.Name = 'buttonBrowseLocation'
	$buttonBrowseLocation.Size = '111, 23'
	$buttonBrowseLocation.TabIndex = 3
	$buttonBrowseLocation.Text = 'Browse Location'
	$buttonBrowseLocation.UseCompatibleTextRendering = $True
	$buttonBrowseLocation.UseVisualStyleBackColor = $True
	$buttonBrowseLocation.add_Click($buttonBrowseLocation_Click)
	#
	# labelLocation
	#
	$labelLocation.AutoSize = $True
	$labelLocation.Location = '7, 18'
	$labelLocation.Name = 'labelLocation'
	$labelLocation.Size = '47, 17'
	$labelLocation.TabIndex = 2
	$labelLocation.Text = 'Location'
	$labelLocation.UseCompatibleTextRendering = $True
	$labelLocation.add_Click($labelLocation_Click)
	#
	# textbox1
	#
	$textbox1.Location = '60, 14'
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '192, 20'
	$textbox1.TabIndex = 1
	#
	# buttonFindPermissions
	#
	$buttonFindPermissions.Location = '135, 46'
	$buttonFindPermissions.Name = 'buttonFindPermissions'
	$buttonFindPermissions.Size = '111, 23'
	$buttonFindPermissions.TabIndex = 0
	$buttonFindPermissions.Text = 'Find Permissions'
	$buttonFindPermissions.UseCompatibleTextRendering = $True
	$buttonFindPermissions.UseVisualStyleBackColor = $True
	$buttonFindPermissions.add_Click($buttonFindPermissions_Click)
	$formDisplayACL.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formDisplayACL.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formDisplayACL.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formDisplayACL.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formDisplayACL.ShowDialog()

} #End Function

#Call the form
Show-GetACL_psf | Out-Null
